

data_from_table = {"null": "no",
                   # direct
                   "N": "DataFromN",
                   "NN": "DataFromNN",
                   # 8-bits reg
                   "A" : "DataFromRegA",
                   "B" : "DataFromRegB",
                   "C" : "DataFromRegC",
                   "D" : "DataFromRegD",
                   "E" : "DataFromRegE",
                   "H" : "DataFromRegH",
                   "L" : "DataFromRegL",
                   "I" : "DataFromRegI",
                   "R" : "DataFromRegR",
                   # 16-bits reg
                   "AF" : "DataFromRegAF",
                   "BC" : "DataFromRegBC",
                   "DE" : "DataFromRegDE",
                   "HL" : "DataFromRegHL",
                   "IX" : "DataFromRegIX",
                   "IY" : "DataFromRegIY",
                   "SP" : "DataFromRegSP",
                   "AF'" : "DataFromRegAFp",
                   "BC'" : "DataFromRegBCp",
                   "DE'" : "DataFromRegDEp",
                   "HL'" : "DataFromRegHLp",
                   # 16-bits addr
                   "(BC)" : "DataFromBCaddr",
                   "(DE)" : "DataFromDEaddr",
                   "(HL)" : "DataFromHLaddr",
                   "(NN)" : "DataFromNNaddr",
                   # ???
                   "$+2" : "TO_IMPLEMENT",
                   "$+3" : "TO_IMPLEMENT",
                   "NZ" : "TO_IMPLEMENT",
                   "Z" : "TO_IMPLEMENT",
                   "0" : "TO_IMPLEMENT",
                   "NC" : "TO_IMPLEMENT",
                   "8H" : "TO_IMPLEMENT",
                   "10H" : "TO_IMPLEMENT",
                   "18H" : "TO_IMPLEMENT",
                   "20H" : "TO_IMPLEMENT",
                   "28H" : "TO_IMPLEMENT",
                   "30H" : "TO_IMPLEMENT",
                   "38H" : "TO_IMPLEMENT",
                   "PO" :  "TO_IMPLEMENT",
                   "PE" :  "TO_IMPLEMENT",
                   "P" : "TO_IMPLEMENT",
                   "M" : "TO_IMPLEMENT",

                   # IO addr
                   "(N)" : "DataFromNIOaddr",
                   "(C)" : "DataFromCIOaddr"}

data_to_table = {"null": "no",
                # 8-bits reg
                "A" : "DataToRegA",
                "B" : "DataToRegB",
                "C" : "DataToRegC",
                "D" : "DataToRegD",
                "E" : "DataToRegE",
                "H" : "DataToRegH",
                "L" : "DataToRegL",
                # 16-bits reg
                "AF" : "DataToRegAF",
                "BC" : "DataToRegBC",
                "DE" : "DataToRegDE",
                "HL" : "DataToRegHL",
                "IX" : "DataToRegIX",
                "IY" : "DataToRegIY",
                "SP" : "DataToRegSP",
                "AF'" : "DataToRegAFp",
                "BC'" : "DataToRegBCp",
                "DE'" : "DataToRegDEp",
                "HL'" : "DataToRegHLp",
                # 16-bits addr
                "(BC)" : "DataToBCaddr",
                "(DE)" : "DataToDEaddr",
                "(HL)" : "DataToHLaddr",
                "(NN)" : "DataToNNaddr",
                "(SP)" : "DataToSPaddr",
                # ???
                "$+2" : "TO_IMPLEMENT",
                "$+3" : "TO_IMPLEMENT",
                "NZ" : "TO_IMPLEMENT",
                "Z" : "TO_IMPLEMENT",
                "NC" : "TO_IMPLEMENT",
                "(N)" : "TO_IMPLEMENT",
                "PO" :  "TO_IMPLEMENT",
                "PE" :  "TO_IMPLEMENT",
                "P" : "TO_IMPLEMENT",
                "M" : "TO_IMPLEMENT",
                }